#
# Puppet environment for Master/Agent testing
#
DOMAIN="example.com"
SUBNET="192.168.1"

Vagrant.configure("2") do |config|

  # Set up our environment
  config.vm.provision :shell, :path => "provision.sh"

  # Performance gain
  #config.vm.synced_folder ".", "/vagrant", :nfs => true

  # Puppet master
  config.vm.define :master do |master|
    master.vm.box = "centos6"
    master.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503.box"
    master.vm.hostname = "puppet.#{DOMAIN}"
    master.vm.network :private_network, ip: "#{SUBNET}.10"
    master.vm.network :forwarded_port, guest: 80, host: 8080
  end

  # Puppet node
  config.vm.define :node do |node|
    node.vm.box = "centos6"
    node.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-fusion503.box"
    node.vm.hostname = "node.#{DOMAIN}"
    node.vm.network :private_network, ip: "#{SUBNET}.11"
    node.vm.network :forwarded_port, guest: 80, host: 9090
  end

end
